name: Semgrep

on:
  workflow_dispatch: {}

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Apply Autofix
        run: |
          semgrep --autofix --config="rules.yml" .


